### ISSUE TITLE
Packages without a full module name

### ISSUE THREAD

**Issue by gedw99** [mjl-/gobuild#3]
Just wondering if it possible to support projects without a full module name ?

https://github.com/gedw99/x-git-binary-dummy/blob/main/go.mod

``` 
go: github.com/gedw99/x-git-binary-dummy@v0.0.0-20230316155946-5f4b54637334: github.com/gedw99/x-git-binary-dummy@v0.0.0-20230316155946-5f4b54637334: parsing go.mod:
	module declares its path as: dummy
	        but was required as: github.com/gedw99/x-git-binary-dummy
```

**Comment by mjl-** [comment]
I think this is something the Go toolchain enforces: If you "go install some/pkg", it requires the module to declare its module as some/pkg. But I'm not 100% sure this is the case, or what the reason for it is.

**Comment by gedw99** [comment]
Yep it’s enforced.

will work around by having root have a proper namespace and main inside a folder 

thanks @mjl-
